replicaCount: 3

image:
  repository: eznd/otus-msa-hw2
  pullPolicy: IfNotPresent
  tag: v0.0.6
  command: ["/app/service"]
#  migrateCommand: ["/app/migrate"]
  migrateCommand: ["/wait-for-it.sh"]
  migrateArgs: ["postgres-db-lb.otus-msa-hw2:5432", "-t", "600000000", "--", "/app/migrate"]

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
  tls: []
